### PR TITLE
Transfer pipelines to new drone

### PR DESCRIPTION
**Pull request by tasharnvb**

### CODE REVIEW

**Review by KashifSaadat — APPROVED** [review]
LGTM

**Comment by easternbloc** [comment]
Can we only open PRs with descriptions please. It's good to explain your reasoning.

**Comment by daniel-ac-martin** [comment]
@tasharnvb, @KashifSaadat: This seems to have broken the pipeline. - https://github.com/UKHomeOffice/docker-proxy/pull/8

i.e. The docker build step no longer runs.

**Comment by tasharnvb** [comment]
@daniel-ac-martin It looks fine to me? https://drone.acp.homeoffice.gov.uk/UKHomeOffice/docker-proxy/7/3

**Comment by daniel-ac-martin** [comment]
@tasharnvb: Apologies. Looks like I didn't understand the new interface! Seems a strange design choice.

**Pull request merged**
